"""create initial EMS tables

Revision ID: f44f716bd6e5
Revises: 
Create Date: 2026-07-27 16:34:58.855148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44f716bd6e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=100), nullable=False),
    sa.Column('dept_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('dept_name')
    )
    op.create_index(op.f('ix_departments_dept_id'), 'departments', ['dept_id'], unique=False)
    op.create_table('leave_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('annual_allowance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_leave_types_type_id'), 'leave_types', ['type_id'], unique=False)
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HR', 'MANAGER', 'STAFF', name='roleenum'), nullable=False),
    sa.Column('staff_grade', sa.String(length=20), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_emp_id'), 'employees', ['emp_id'], unique=False)
    op.create_table('attendance',
    sa.Column('att_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('att_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('att_status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('att_id')
    )
    op.create_index(op.f('ix_attendance_att_id'), 'attendance', ['att_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('table_affected', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=False)
    op.create_table('dependents',
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('dep_name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('dep_id')
    )
    op.create_index(op.f('ix_dependents_dep_id'), 'dependents', ['dep_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('balance_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['leave_types.type_id'], ),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_index(op.f('ix_leave_balances_balance_id'), 'leave_balances', ['balance_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['leave_types.type_id'], ),
    sa.PrimaryKeyConstraint('leave_id')
    )
    op.create_index(op.f('ix_leave_requests_leave_id'), 'leave_requests', ['leave_id'], unique=False)
    op.create_table('payroll',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('payroll_id')
    )
    op.create_index(op.f('ix_payroll_payroll_id'), 'payroll', ['payroll_id'], unique=False)
    op.create_table('approval_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('approved_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['leave_id'], ['leave_requests.leave_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_approval_logs_log_id'), 'approval_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_logs_log_id'), table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_payroll_payroll_id'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_index(op.f('ix_leave_requests_leave_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_balance_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_dependents_dep_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_att_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_employees_emp_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_leave_types_type_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_departments_dept_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
